In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression,Lasso,ElasticNet,Ridge
from sklearn.ensemble import RandomForestRegressor

In [2]:
df=load_diabetes()

In [3]:
df

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [4]:
x=pd.DataFrame(data=df.data,columns=df.feature_names)

In [5]:
x

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [6]:
y=pd.DataFrame(df["target"])

In [7]:
y

         0
0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
..     ...
437  178.0
438  104.0
439  132.0
440  220.0
441   57.0

[442 rows x 1 columns]

In [8]:
y = np.ravel(y)

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=32)

## Ada Boosting --> Regression

In [10]:
%%time
Ada_boost=AdaBoostRegressor(n_estimators=250)
Ada_boost.fit(x_train,y_train)
y_train_pred=Ada_boost.predict(x_train)
print("Train Score :",r2_score(y_train,y_train_pred))
y_test_pred=Ada_boost.predict(x_test)
print("Test Score :",r2_score(y_test,y_test_pred))

Train Score : 0.6134506313945025
Test Score : 0.4786519957549614
CPU times: total: 188 ms
Wall time: 215 ms

## Gradient Boosting --> Regression

In [11]:
%%time
Grad_boost=GradientBoostingRegressor(n_estimators=150)
Grad_boost.fit(x_train,y_train)
y_train_pred=Grad_boost.predict(x_train)
print("Train Score :",r2_score(y_train,y_train_pred))
y_test_pred=Grad_boost.predict(x_test)
print("Test Score :",r2_score(y_test,y_test_pred))

Train Score : 0.8860506066063567
Test Score : 0.31596396435286456
CPU times: total: 312 ms
Wall time: 330 ms

## Linear Regression

In [12]:
%%time
Linearregression=LinearRegression()
Linearregression.fit(x_train,y_train)
y_train_pred=Linearregression.predict(x_train)
y_test_pred=Linearregression.predict(x_test)
print("Train Score :",r2_score(y_train,y_train_pred))
print("Test Score :",r2_score(y_test,y_test_pred))

Train Score : 0.5275747680841016
Test Score : 0.45223387963545714
CPU times: total: 15.6 ms
Wall time: 34.5 ms

## Random Forest ---> Regression

In [13]:
%%time
RF_model= RandomForestRegressor(n_estimators=150)
RF_model.fit(x_train,y_train)
y_train_pred=RF_model.predict(x_train)
y_test_pred=RF_model.predict(x_test)
print("Train Score :",r2_score(y_train,y_train_pred))
print("Test Score :",r2_score(y_test,y_test_pred))

Train Score : 0.9193742503559058
Test Score : 0.4394460807214511
CPU times: total: 641 ms
Wall time: 654 ms

In [14]:
pip install xgboost

Requirement already satisfied: xgboost in C:\Users\Logeshwaran S\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.4.1)
Requirement already satisfied: numpy in C:\Users\Logeshwaran S\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (2.5.1)
Requirement already satisfied: scipy in C:\Users\Logeshwaran S\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (1.18.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
XGB_boost=XGBRegressor()
param_grid={"gamma":[0.01,0.02,0.03,0.1,0.2,0.3,1,1.1,1.2,1.3],"learning_rate":[0.1,0.2,0.3,0.4,0.5,0.8,1,1.1,1.2,1.3],"reg_lambda":[0.01,0.02,0.03,0.1,0.2,0.3,1,1.1,1.2,1.3]}

In [18]:
G_SCV=GridSearchCV(estimator=XGB_boost,param_grid=param_grid,cv=5)

In [ ]:
G_SCV.fit(x_train,y_train)

In [23]:
G_SCV.best_params_

{'gamma': 1, 'learning_rate': 0.2, 'reg_lambda': 1.3}

In [17]:
y_test_pred=G_SCV.predict(x_test)

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [25]:
from sklearn.metrics import r2_score

In [26]:
r2_score(y_test,y_test_pred)

0.3086412501118999

In [44]:
XGB_boost1=XGBRegressor(gamma=1,learning_rate=0.2,reg_lambda=1.3,max_depth=10)

In [45]:
XGB_boost1.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=1, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.2, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [46]:
y_train_pred=XGB_boost1.predict(x_train)

In [47]:
y_test_pred=XGB_boost1.predict(x_test)

In [58]:
print("r2_score of train data :",r2_score(y_train,y_train_pred))

Training Score : 0.8950146382552268

In [59]:
print("r2_score of test data :",r2_score(y_test,y_test_pred))

Testing Score : 0.3592104448150918

from xgboost import XGBRFRegressor
from sklearn.model_selection import GridSearchCV
XGBRF_boost=XGBRegressor()
param_grid={"gamma":[0.01,0.02,0.03,0.1,0.2,0.3,1,1.1,1.2,1.3],"learning_rate":[0.1,0.2,0.3,0.4,0.5,0.8,1,1.1,1.2,1.3],"reg_lambda":[0.01,0.02,0.03,0.1,0.2,0.3,1,1.1,1.2,1.3]}

G_SCV1=GridSearchCV(estimator=XGBRF_boost,param_grid=param_grid,cv=5)

G_SCV1.fit(x_train,y_train)

G_SCV.best_params_

In [ ]:
# pip install Lightgbm

In [50]:
pip install Lightgbm

Collecting Lightgbm
  Downloading lightgbm-4.7.0-py3-none-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: narwhals>=1.15 in C:\Users\sarav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Lightgbm) (2.24.0)
Requirement already satisfied: numpy>=1.21.3 in C:\Users\sarav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Lightgbm) (2.3.2)
Requirement already satisfied: scipy in C:\Users\sarav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Lightgbm) (1.18.0)
Downloading lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 454.5 kB/s eta 0:00:02
   --------------- ------------------------ 0.5/1.4 MB 454.5 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 515.6 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 515.6 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 515.6 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 500.0 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 500.0 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 500.0 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 500.0 kB/s eta 0:00:01
   -------------------------------------- - 1.3/1.4 MB 420.4 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 421.8 kB/s  0:00:03
Installing collected packages: Lightgbm
Successfully installed Lightgbm-4.7.0
Note: you may need to restart the kernel to use updated packages.

In [51]:
from lightgbm import LGBMRegressor

In [52]:
light_model=LGBMRegressor(max_depth=6,num_leaves=20)

In [53]:
%%time
light_model.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000272 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 592
[LightGBM] [Info] Number of data points in the train set: 353, number of used features: 10
[LightGBM] [Info] Start training from score 153.524079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
CPU times: total: 188 ms
Wall time: 2.85 s

LGBMRegressor(max_depth=6, num_leaves=20)

In [54]:
y_train_pred=light_model.predict(x_train)

In [55]:
y_test_pred=light_model.predict(x_test)

In [60]:
print("r2_score of train data :",r2_score(y_train,y_train_pred))

Training Score : 0.8950146382552268

In [61]:
print("r2_score of test data :",r2_score(y_test,y_test_pred))

Testing Score : 0.3592104448150918

## To Avoid Overfitting in Linear Regression ---> We can go with regularization Algorithms

To Add Penalty , which is Lambda.
1. Lasso
2. Elastic Net
3. Ridge

In [62]:
from sklearn.linear_model import LinearRegression,Lasso,ElasticNet,Ridge

In [63]:
%%time
Linearregression=LinearRegression()
Linearregression.fit(x_train,y_train)
y_train_pred=Linearregression.predict(x_train)
y_test_pred=Linearregression.predict(x_test)

CPU times: total: 15.6 ms
Wall time: 7.16 ms

In [64]:
print("r2_score  of train data :",r2_score(y_train,y_train_pred))

r2_score  of train data : 0.5275747680841016

In [65]:
print("r2_score  of test data :",r2_score(y_test,y_test_pred))

r2_score  of test data : 0.45223387963545714

## Using Lasso regression

In [66]:
Lasso_regression=Lasso()
Lasso_regression.fit(x_train,y_train)
y_train_pred=Lasso_regression.predict(x_train)
print("r2_score of train data :",r2_score(y_train,y_train_pred))
y_test_pred=Lasso_regression.predict(x_test)
print("r2_score of test data :",r2_score(y_test,y_test_pred))

r2_score of train data : 0.36825597919871966
r2_score of test data : 0.36468849237861767

## Using Elastic Net

In [67]:
Elastic_regression=ElasticNet()
Elastic_regression.fit(x_train,y_train)
y_train_pred=Elastic_regression.predict(x_train)
print("r2_score of train data :",r2_score(y_train,y_train_pred))
y_test_pred=Elastic_regression.predict(x_test)
print("r2_score of test data :",r2_score(y_test,y_test_pred))

r2_score of train data : 0.009117132342753798
r2_score of test data : 0.00010115010488997989

## Using Ridge Regression

In [68]:
Ridge_regression=Ridge()
Ridge_regression.fit(x_train,y_train)
y_train_pred=Ridge_regression.predict(x_train)
print("r2_score of train data :",r2_score(y_train,y_train_pred))
y_test_pred=Ridge_regression.predict(x_test)
print("r2_score of test data :",r2_score(y_test,y_test_pred))

r2_score of train data : 0.44467986070578813
r2_score of test data : 0.408782770933115

### To check which model out of 3 is best that one is choose to implement in boosting  ---> This is used for improve the Accuracy

In [69]:
model=AdaBoostRegressor(estimator=Lasso_regression,n_estimators=250)
model.fit(x_train,y_train)
y_train_pred=model.predict(x_train)
print("r2_score of AdaBoost in train data :",r2_score(y_train,y_train_pred))
y_test_pred=model.predict(x_test)
print("r2_score of AdaBoost in test data :",r2_score(y_test,y_test_pred))

r2_score of AdaBoost in train data : 0.417243848299113
r2_score of AdaBoost in test data : 0.39091283876189864